hyperscan: support aarch64 platform
kunpengcompute/hyperscan pull request #1
Opened 2020-01-15 08:46 UTC by tqltech

Add aarch64 platform branch, which is fully compatible with armv8-a, and at the same time ensure that the use of x86 platform is not affected.

The modification can be divided into the following aspects :
(1) CMakeLists.txt: add branches to judge x86 and aaarch64 platforms.
(2) simd_arm.h: Use the neon instruction to implement 128 operation functions.
(3) simd_x86.h: Save the original simd_utils.h file contents.
(4) simd_utils.h: Select different header files (simd_x86.h or simd_arm.h) according to the platform judgment results.
(5) Intrinsic function: There are multiple calls to the intrinsic function in the code, and the intrinsic function is encapsulated in the modification.
(6) control_verbs.cpp / ExpressionParser.cpp / control_verbs.cpp / Parser.cpp: There are errors in generating these four files under the aarch64 platform. So the files are generated on the x86 platform and copied to the corresponding directory for use. Does not affect the functionality of the x86 platform.

2020-01-16 01:32 UTC, bzhaoopenstack commented
Let's wait for the feedback from upstream side. I'm trying to create a connection with them. If upstream team could review and give some reviews, I'm afraid that the code should be changed. So this PR IMO, leave it here for now.

2020-01-17 02:41 UTC, bzhaoopenstack reviewed
These reviews could be hold here, just for marking, these won't stop this patch to be merged.

2020-01-17 02:41 UTC, bzhaoopenstack commented on CMakeLists.txt
> +option(BUILD_AVX512 "Experimental: support avx512 in the fat runtime"
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on CMakeLists.txt
> +	else()
The indentation of this line is not aligned with the L350

2020-01-17 02:41 UTC, bzhaoopenstack commented on CMakeLists.txt
> +
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on CMakeLists.txt
> +
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on tools/hscollider/ColliderCorporaParser.cpp
> +
code begins from top of a file

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> +template <class Mask>
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> +template <typename T>
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> +            m256 x = setbit<m256>(j * 32 + i);
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> +            ASSERT_EQ(1U << j, diffrich256(x, y)) << "bit " << j * 32 + i << " not happy";
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> +                << "bit " << i << " is wrong";
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> -
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> -
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> +    u32 cmp[4] = {0x12345678, 0x12345678, 0x12345678, 0x12345678};
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> +        !diff128(lshiftbyte_m128(in, 10), variable_byte_shift_m128(in, 10)));
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> +                             0x30, 0x30, 0x30, 0x30, 0,    0,    0,    0};
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> +                             'a', 'b',  'c',  'd',  '1', '2', '3', '4'};
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on unit/internal/simd_utils.cpp
> +                             0x30, 0x30, 0x30, 0x30, 0,    0,    0,    0};
Mark for unecessary change

2020-01-17 02:41 UTC, bzhaoopenstack commented on util/ExpressionParser.cpp
> +
code should begin from the top of a file

2020-01-17 02:53 UTC, Yikun requested changes

2020-01-17 02:53 UTC, Yikun commented on CMakeLists.txt
> +option(BUILD_AVX512 "Experimental: support avx512 in the fat runtime"
Could we cleanup unrealated changes?

2020-01-17 02:53 UTC, Yikun commented on CMakeLists.txt
> +        if (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|i386")
I just wanna sure does it include all PROCESSOR flags which we want to cover? i386|i686|amd64|x86_64|AMD64

See ref in [1]

[1] https://github.com/ceph/ceph/blob/master/cmake/modules/SIMDExt.cmake#L48

2020-01-17 02:53 UTC, Yikun commented on CMakeLists.txt
> +
unrelated new line

2020-01-17 08:45 UTC, closed without merging